### PR TITLE
Recursively merge all the things

### PR DESCRIPTION
**Pull request by chrishunt**
See commits for details

### CODE REVIEW

**Comment by chrishunt** [comment]
Dang. I see you _just_ merged a refactor :)

**Comment by steveklabnik** [comment]
:'( Yeah. Sorry, I didn't know this was incoming!

**Comment by steveklabnik** [comment]
This might still be valuable, though: do those two tests fail without the rest of the patch?

**Comment by chrishunt** [comment]
Those tests are required to verify https://github.com/steveklabnik/json-merge_patch/blob/master/lib/json/merge_patch.rb#L97

I just noticed that I could delete that line and nothing failed

**Comment by steveklabnik** [comment]
Right. Awesome. I had a feeling that I was missing some edge cases, but wasn't 100% sure.

**Comment by chrishunt** [comment]
Let me rebase, master changed.

**Comment by chrishunt** [comment]
There you are sir

**Comment by steveklabnik** [comment]
Thank you very much!

**Comment by chrishunt** [comment]
4.0 GPA :100: :tada:

**Pull request merged**
