### PR TITLE
Quick readme fix...

### PR DESCRIPTION
**Pull request by jasnell**
In the example result, the new phone number field is a child of the top level doc, not the "author" element... just checking the readme on this, need to check to make sure the impl handles that correctly.. also, the title result should be "Hello!" not "Goodbye!"

### CODE REVIEW

**Comment by steveklabnik** [comment]
I copied it straight from the draft, so unless I messed that up...

The draft might be wrong. o_O
—

**Comment by jasnell** [comment]
Just double checked the draft [1] ... it shows the example result as:

```
         {
           "title": "Hello!",
           "author" : {
             "givenName" : "John"
           },
           "tags":["example"],
           "content": "This will be unchanged",
           "phoneNumber": "+01-123-456-7890"
         }
```

[1] http://tools.ietf.org/html/draft-snell-merge-patch-08

**Comment by steveklabnik** [comment]
Apparently I can't copy/paste then.
—

**Comment by steveklabnik** [comment]
Can you update/check the test too?
—

**Comment by jasnell** [comment]
lol.. yeah I'll take a look shortly.

**Comment by steveklabnik** [comment]
<3

**Comment by jasnell** [comment]
Took a bit longer than I expected, but I finally had a chance to look at the test case and it looks good!

**Comment by steveklabnik** [comment]
No worries. I was mobile at the time, or I would have checked myself. <3

**Pull request merged**
