### PR TITLE
Don't delete nulls inside Arrays

### PR DESCRIPTION
**Pull request by chrishunt**
> **Part 3**
> If the value is either a non-null JSON primitive or an Array and that member
> is currently defined within the target resource, the existing value for that
> member is to be replaced with that provided. **Any object member contained in
> the provided data whose value is explicitly null is to be treated as if the
> member were undefined**

This could go either way, but it reads to me like we want to remove `null` _members_, but not necessarily nulls inside of Arrays.

Since Arrays are replaced entirely every time we patch, null doesn't have any special meaning inside an Array; it's just data.

Either way, [line #69](https://github.com/steveklabnik/json-merge_patch/blob/3067a80627499ffedbdf474dd1c2d62c8bd2d872/lib/json/merge_patch.rb#L69) can be deleted without failing any tests. We should modify the test in this PR to match whatever behavior we think is best. The implementation in this PR will allow nulls inside Arrays.

### CODE REVIEW

**Comment by steveklabnik** [comment]
We're actually discussing this on the IETF list right now...

**Comment by chrishunt** [comment]
Cool. I'm curious to hear what happens. I tried googling for the list, but there are a TON of lists on http://www.ietf.org and search is failing me.

**Comment by steveklabnik** [comment]
Ahh look: http://www.ietf.org/mail-archive/web/apps-discuss/current/msg09496.html

**Comment by chrishunt** [comment]
Thanks for the link. Sounds like it could go either way.

**Comment by jasnell** [comment]
Recommend keeping this open. The intent has always been to purge all nulls from the final result, obviously if there is consensus from the appsawg to change that, I will do so, but I'd rather not.

**Comment by steveklabnik** [comment]
Sounds good!

**Comment by chrishunt** [comment]
Closing this, it's super old. Re-open later if you want :heart:

**Pull request closed without merging**
